CHANGE(grafana): Provision 2 new diagnostic dashboards
open-io/ansible-role-openio-grafana pull request #25
Opened 2019-06-07 08:16 UTC by fatpat

##### SUMMARY
- diag_host_details: to view system details about one single host
- diag_hosts_comparison: to compare metrics between hosts

 ##### ISSUE TYPE
- Feature Pull Request

2019-06-07 08:26 UTC, vdombrovski requested changes
Please import dashboards using provided tools/retriever.py script

2019-06-07 08:38 UTC, fatpat commented
> Please import dashboards using provided tools/retriever.py script

done

2019-06-10 10:00 UTC, vdombrovski requested changes

2019-06-10 10:00 UTC, vdombrovski commented on files/diag_host_details.json
> +              "expr": "sum(aggr:netdata_web_log_http_request_methods:sum{instance=~\"$host\",chart2=\"RAKUTEN.oioswift\"}) by (dimension)",
Hardcoded NS

2019-06-10 10:00 UTC, vdombrovski commented on files/diag_host_details.json
> +              "expr": "sum(aggr:netdata_web_log_http_request_methods:sum{instance=~\"$host\",chart2=\"RAKUTEN.meta1\"}) by (dimension)",
Hardcoded NS

2019-06-10 10:00 UTC, vdombrovski commented on files/diag_host_details.json
> +              "expr": "sum(aggr:netdata_web_log_http_request_methods:sum{instance=~\"$host\",chart2=\"RAKUTEN.rawx\"}) by (dimension)",
Hardcoded NS

2019-06-10 10:00 UTC, vdombrovski commented on files/diag_host_details.json
> +              "expr": "sum(aggr:netdata_web_log_http_request_methods:sum{instance=~\"$host\",chart2=\"RAKUTEN.meta2\"}) by (dimension)",
Hardcoded NS

2019-06-10 10:00 UTC, vdombrovski commented on files/diag_host_details.json
> +          "expr": "sum(netdata_apps_cpu_system_cpu_time___average{chart=\"apps.cpu_system\",family=\"cpu\",instance=~\"$host$\"}) by (dimension)",
Wrong percentage display (should be percent 0.0-1.0)

2019-06-10 10:00 UTC, vdombrovski commented on files/diag_hosts_comparison.json
> +              "expr": "sum(netdata_apps_cpu_system_cpu_time___average{chart=\"apps.cpu_system\",family=\"cpu\",instance=~\"$host$\"}) by (dimension)",
Wrong percentage display

2019-06-10 10:02 UTC, vdombrovski commented
Besides fixes, this PR only adds to dashboards to maintain without giving much more new information (all info can be found in other dashboards).

I am against integrating it into release until we don't have proper QA auto-validating dashboard queries.

2019-08-18 20:47 UTC, cdelgehier commented
ping @fatpat

2019-09-17 12:05 UTC, closed without merging